import {
  ActivityEntry,
  AssignmentCard,
  AuditLogEntry,
  AuthRecord,
  AuthorityUser,
  BroadcastAlert,
  Conversation,
  Incident,
  NgoOrganization,
  NotificationItem,
  ResourceInventoryItem,
  Role,
  SupportRequest,
  Volunteer,
} from "@/sos/models";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60 * 1000).toISOString();

export const demoAuthRecords: AuthRecord[] = [
  {
    id: "auth-001",
    role: "authority",
    email: "authority@sos.gov",
    password: "authority123",
    name: "Commissioner Anita Rao",
    organization: "District Emergency Command",
  },
  {
    id: "ngo-001",
    role: "ngo",
    email: "ngo@sos.org",
    password: "ngo123",
    name: "Ayaan Mehta",
    organization: "Rapid Aid Collective",
  },
];

export const authorityUsers: AuthorityUser[] = [
  { id: "au-1", name: "Rahul Verma", role: "Duty Officer", online: true, district: "Central" },
  { id: "au-2", name: "Meera Pillai", role: "Field Coordinator", online: true, district: "West" },
  { id: "au-3", name: "S. Khan", role: "Verification Lead", online: false, district: "North" },
  { id: "au-4", name: "Nisha Kapoor", role: "Escalation Desk", online: true, district: "East" },
];

export const ngoOrganizations: NgoOrganization[] = [
  {
    id: "ngo-01",
    name: "Rapid Aid Collective",
    services: ["medical", "rescue", "shelter"],
    coverageAreas: ["Central", "North", "East"],
    availability: "available",
    capacity: 82,
    contactPerson: "Ayaan Mehta",
    contactPhone: "+1-202-555-0101",
    reliabilityScore: 4.8,
    activeCases: 16,
  },
  {
    id: "ngo-02",
    name: "Urban Relief Network",
    services: ["food", "shelter", "child-support"],
    coverageAreas: ["South", "West"],
    availability: "limited",
    capacity: 64,
    contactPerson: "Riya Singh",
    contactPhone: "+1-202-555-0102",
    reliabilityScore: 4.5,
    activeCases: 11,
  },
  {
    id: "ngo-03",
    name: "Women Safe Response",
    services: ["women-support", "legal-aid", "medical"],
    coverageAreas: ["Central", "West"],
    availability: "available",
    capacity: 71,
    contactPerson: "Leena Das",
    contactPhone: "+1-202-555-0103",
    reliabilityScore: 4.9,
    activeCases: 8,
  },
  {
    id: "ngo-04",
    name: "Civic Rescue Trust",
    services: ["rescue", "transport", "oxygen"],
    coverageAreas: ["North", "South", "East"],
    availability: "offline",
    capacity: 42,
    contactPerson: "Harshit Jain",
    contactPhone: "+1-202-555-0104",
    reliabilityScore: 4.2,
    activeCases: 4,
  },
];

export const incidents: Incident[] = [
  {
    id: "INC-2401",
    title: "Road collision with injuries",
    description: "Two-vehicle collision near metro underpass with multiple injuries.",
    category: "medical",
    priority: "critical",
    status: "assigned",
    verificationStatus: "verified",
    source: "call-center",
    location: { area: "Metro Underpass", district: "Central", city: "Springfield", lat: 38.889, lng: -77.035 },
    assignedNgoIds: ["ngo-01"],
    assignedTeam: "City EMT Team-4",
    updatesCount: 12,
    commentsCount: 7,
    attachments: ["/placeholder.svg", "/placeholder.svg"],
    createdAt: minutesAgo(40),
    updatedAt: minutesAgo(6),
    etaMinutes: 9,
    slaMinutes: 30,
  },
  {
    id: "INC-2402",
    title: "Fire in informal settlement",
    description: "Cluster fire reported near Ward 7, evacuation in progress.",
    category: "fire",
    priority: "critical",
    status: "in-progress",
    verificationStatus: "verified",
    source: "citizen",
    location: { area: "Ward 7", district: "West", city: "Springfield", lat: 38.901, lng: -77.043 },
    assignedNgoIds: ["ngo-04", "ngo-02"],
    assignedTeam: "Fire Ops 2",
    updatesCount: 18,
    commentsCount: 13,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(8),
    etaMinutes: 6,
    slaMinutes: 25,
  },
  {
    id: "INC-2403",
    title: "Missing child support alert",
    description: "Child assistance requested at bus depot, crowd support needed.",
    category: "child-help",
    priority: "high",
    status: "open",
    verificationStatus: "pending",
    source: "app",
    location: { area: "North Bus Depot", district: "North", city: "Springfield", lat: 38.912, lng: -77.051 },
    assignedNgoIds: [],
    assignedTeam: "Unassigned",
    updatesCount: 3,
    commentsCount: 2,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(21),
    updatedAt: minutesAgo(21),
    etaMinutes: 20,
    slaMinutes: 45,
  },
  {
    id: "INC-2404",
    title: "Flooded lane, families stranded",
    description: "Heavy rain waterlogging, rescue boat requested for 30 residents.",
    category: "disaster",
    priority: "high",
    status: "verified",
    verificationStatus: "verified",
    source: "officer",
    location: { area: "Riverbank Lane", district: "East", city: "Springfield", lat: 38.877, lng: -77.012 },
    assignedNgoIds: ["ngo-01"],
    assignedTeam: "Flood Response Unit",
    updatesCount: 9,
    commentsCount: 4,
    attachments: ["/placeholder.svg", "/placeholder.svg"],
    createdAt: minutesAgo(165),
    updatedAt: minutesAgo(42),
    etaMinutes: 14,
    slaMinutes: 40,
  },
  {
    id: "INC-2405",
    title: "Women safety distress at rail stop",
    description: "Harassment report received from station helpline kiosk.",
    category: "women-safety",
    priority: "high",
    status: "assigned",
    verificationStatus: "verified",
    source: "call-center",
    location: { area: "Grand Rail Stop", district: "Central", city: "Springfield", lat: 38.886, lng: -77.028 },
    assignedNgoIds: ["ngo-03"],
    assignedTeam: "Safety Patrol S2",
    updatesCount: 10,
    commentsCount: 5,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(120),
    updatedAt: minutesAgo(35),
    etaMinutes: 11,
    slaMinutes: 30,
  },
  {
    id: "INC-2406",
    title: "Community kitchen shortage",
    description: "Food packets exhausted in temporary shelter zone B.",
    category: "food-support",
    priority: "medium",
    status: "open",
    verificationStatus: "pending",
    source: "app",
    location: { area: "Shelter Zone B", district: "South", city: "Springfield", lat: 38.865, lng: -77.067 },
    assignedNgoIds: [],
    assignedTeam: "Unassigned",
    updatesCount: 2,
    commentsCount: 1,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(31),
    updatedAt: minutesAgo(31),
    etaMinutes: 22,
    slaMinutes: 55,
  },
  {
    id: "INC-2407",
    title: "Building collapse rescue",
    description: "Partial collapse after gas leak, trapped residents suspected.",
    category: "rescue",
    priority: "critical",
    status: "in-progress",
    verificationStatus: "verified",
    source: "officer",
    location: { area: "Pine Block C", district: "West", city: "Springfield", lat: 38.897, lng: -77.064 },
    assignedNgoIds: ["ngo-01", "ngo-04"],
    assignedTeam: "Urban Search Team",
    updatesCount: 25,
    commentsCount: 15,
    attachments: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    createdAt: minutesAgo(210),
    updatedAt: minutesAgo(12),
    etaMinutes: 5,
    slaMinutes: 20,
  },
  {
    id: "INC-2408",
    title: "Temporary shelter overcrowding",
    description: "Need extra tents and blankets for displaced families.",
    category: "shelter",
    priority: "medium",
    status: "resolved",
    verificationStatus: "verified",
    source: "citizen",
    location: { area: "Community Grounds", district: "East", city: "Springfield", lat: 38.881, lng: -77.004 },
    assignedNgoIds: ["ngo-02"],
    assignedTeam: "Shelter Desk",
    updatesCount: 6,
    commentsCount: 3,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(390),
    updatedAt: minutesAgo(53),
    etaMinutes: 0,
    slaMinutes: 90,
  },
  {
    id: "INC-2409",
    title: "Medical refill request",
    description: "Urgent insulin and antibiotics needed in field clinic.",
    category: "medical",
    priority: "high",
    status: "verified",
    verificationStatus: "verified",
    source: "officer",
    location: { area: "Field Clinic 3", district: "North", city: "Springfield", lat: 38.921, lng: -77.022 },
    assignedNgoIds: ["ngo-01"],
    assignedTeam: "Medical Logistics",
    updatesCount: 7,
    commentsCount: 2,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(260),
    updatedAt: minutesAgo(49),
    etaMinutes: 17,
    slaMinutes: 50,
  },
  {
    id: "INC-2410",
    title: "Resolved evacuation support",
    description: "Elderly residents moved to safe center with oxygen support.",
    category: "rescue",
    priority: "low",
    status: "closed",
    verificationStatus: "verified",
    source: "call-center",
    location: { area: "Maple Apartments", district: "South", city: "Springfield", lat: 38.859, lng: -77.058 },
    assignedNgoIds: ["ngo-04", "ngo-01"],
    assignedTeam: "Support Unit",
    updatesCount: 16,
    commentsCount: 9,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(780),
    updatedAt: minutesAgo(310),
    etaMinutes: 0,
    slaMinutes: 120,
  },
  {
    id: "INC-2411",
    title: "Suspected duplicate flooding report",
    description: "Incoming signal overlaps with INC-2404 area and timeline.",
    category: "disaster",
    priority: "medium",
    status: "open",
    verificationStatus: "duplicate",
    source: "app",
    location: { area: "Riverbank Lane", district: "East", city: "Springfield", lat: 38.878, lng: -77.01 },
    assignedNgoIds: [],
    assignedTeam: "Unassigned",
    updatesCount: 1,
    commentsCount: 1,
    attachments: ["/placeholder.svg"],
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
    etaMinutes: 0,
    slaMinutes: 35,
  },
  {
    id: "INC-2412",
    title: "Night shelter unsafe access",
    description: "Access road blocked, women and children waiting outside shelter.",
    category: "shelter",
    priority: "high",
    status: "assigned",
    verificationStatus: "verified",
    source: "citizen",
    location: { area: "Old Mill Road", district: "West", city: "Springfield", lat: 38.902, lng: -77.071 },
    assignedNgoIds: ["ngo-03", "ngo-02"],
    assignedTeam: "Road Clearance Team",
    updatesCount: 8,
    commentsCount: 6,
    attachments: ["/placeholder.svg", "/placeholder.svg"],
    createdAt: minutesAgo(130),
    updatedAt: minutesAgo(18),
    etaMinutes: 13,
    slaMinutes: 45,
  },
];

export const volunteers: Volunteer[] = [
  {
    id: "vol-1",
    organizationId: "ngo-01",
    name: "Nikhil Rana",
    role: "medic",
    status: "available",
    skills: ["trauma-care", "triage"],
    assignedTaskCount: 2,
    shift: "08:00 - 16:00",
  },
  {
    id: "vol-2",
    organizationId: "ngo-01",
    name: "Rosa Diaz",
    role: "driver",
    status: "on-mission",
    skills: ["ambulance", "navigation"],
    assignedTaskCount: 1,
    shift: "06:00 - 14:00",
  },
  {
    id: "vol-3",
    organizationId: "ngo-02",
    name: "Karan Bhatia",
    role: "coordinator",
    status: "available",
    skills: ["logistics", "dispatch"],
    assignedTaskCount: 4,
    shift: "09:00 - 17:00",
  },
  {
    id: "vol-4",
    organizationId: "ngo-03",
    name: "Fatima Noor",
    role: "field-volunteer",
    status: "offline",
    skills: ["community-support", "documentation"],
    assignedTaskCount: 0,
    shift: "12:00 - 20:00",
  },
  {
    id: "vol-5",
    organizationId: "ngo-04",
    name: "Sahil Khurana",
    role: "driver",
    status: "on-mission",
    skills: ["heavy-vehicle", "rescue-transport"],
    assignedTaskCount: 3,
    shift: "00:00 - 08:00",
  },
  {
    id: "vol-6",
    organizationId: "ngo-03",
    name: "Tina Dsouza",
    role: "coordinator",
    status: "available",
    skills: ["women-support", "legal-aid"],
    assignedTaskCount: 2,
    shift: "14:00 - 22:00",
  },
];

export const resourceInventory: ResourceInventoryItem[] = [
  {
    id: "res-1",
    organizationId: "ngo-01",
    resource: "Medicines",
    available: 320,
    reserved: 80,
    unit: "kits",
    minThreshold: 120,
    updatedAt: minutesAgo(20),
  },
  {
    id: "res-2",
    organizationId: "ngo-01",
    resource: "Rescue kits",
    available: 64,
    reserved: 21,
    unit: "kits",
    minThreshold: 30,
    updatedAt: minutesAgo(42),
  },
  {
    id: "res-3",
    organizationId: "ngo-02",
    resource: "Food packets",
    available: 480,
    reserved: 210,
    unit: "packets",
    minThreshold: 250,
    updatedAt: minutesAgo(11),
  },
  {
    id: "res-4",
    organizationId: "ngo-02",
    resource: "Blankets",
    available: 130,
    reserved: 95,
    unit: "units",
    minThreshold: 80,
    updatedAt: minutesAgo(34),
  },
  {
    id: "res-5",
    organizationId: "ngo-03",
    resource: "Shelter slots",
    available: 38,
    reserved: 34,
    unit: "slots",
    minThreshold: 15,
    updatedAt: minutesAgo(28),
  },
  {
    id: "res-6",
    organizationId: "ngo-04",
    resource: "Oxygen cylinders",
    available: 15,
    reserved: 11,
    unit: "cylinders",
    minThreshold: 9,
    updatedAt: minutesAgo(55),
  },
  {
    id: "res-7",
    organizationId: "ngo-04",
    resource: "Vehicles",
    available: 5,
    reserved: 5,
    unit: "vehicles",
    minThreshold: 4,
    updatedAt: minutesAgo(75),
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "not-1",
    role: "authority",
    type: "incident-assigned",
    title: "NGO acknowledged INC-2405",
    description: "Women Safe Response accepted assignment for Grand Rail Stop.",
    read: false,
    linkedPath: "/authority/requests/INC-2405",
    createdAt: minutesAgo(4),
    priority: "high",
  },
  {
    id: "not-2",
    role: "authority",
    type: "case-escalated",
    title: "Escalation queued: INC-2407",
    description: "SLA risk in 5 minutes. Additional rescue unit suggested.",
    read: false,
    linkedPath: "/authority/escalations",
    createdAt: minutesAgo(7),
    priority: "critical",
  },
  {
    id: "not-3",
    role: "ngo",
    type: "incident-assigned",
    title: "New assignment INC-2404",
    description: "Flood response case assigned to Rapid Aid Collective.",
    read: false,
    linkedPath: "/ngo/requests/INC-2404",
    createdAt: minutesAgo(9),
    priority: "high",
  },
  {
    id: "not-4",
    role: "ngo",
    type: "resource-update",
    title: "Low stock warning",
    description: "Food packets below buffer in South district shelter cluster.",
    read: true,
    linkedPath: "/ngo/resources",
    createdAt: minutesAgo(27),
    priority: "medium",
  },
  {
    id: "not-5",
    role: "all",
    type: "broadcast-alert",
    title: "Weather advisory broadcast",
    description: "Heavy rain expected in West and East sectors for next 6 hours.",
    read: false,
    linkedPath: "/authority/announcements",
    createdAt: minutesAgo(30),
    priority: "high",
  },
  {
    id: "not-6",
    role: "authority",
    type: "verification-complete",
    title: "Verification complete INC-2402",
    description: "Field unit uploaded final evidence set.",
    read: true,
    linkedPath: "/authority/approvals",
    createdAt: minutesAgo(62),
    priority: "medium",
  },
  {
    id: "not-7",
    role: "ngo",
    type: "message",
    title: "Authority message in Ops Command",
    description: "Requesting revised ETA for INC-2404 response.",
    read: false,
    linkedPath: "/ngo/messages",
    createdAt: minutesAgo(13),
    priority: "medium",
  },
  {
    id: "not-8",
    role: "all",
    type: "comment-added",
    title: "New note added",
    description: "Pinned update posted in INC-2401 timeline.",
    read: true,
    linkedPath: "/authority/requests/INC-2401",
    createdAt: minutesAgo(80),
    priority: "low",
  },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    title: "INC-2404 Flood Ops",
    participants: ["Authority Desk", "Rapid Aid Collective", "Field Unit East"],
    participantRoles: ["authority", "ngo", "team"],
    incidentId: "INC-2404",
    unreadCount: 2,
    updatedAt: minutesAgo(5),
    messages: [
      {
        id: "msg-1",
        conversationId: "conv-1",
        sender: "Authority Desk",
        senderRole: "authority",
        text: "Need updated boat dispatch ETA for Riverbank Lane.",
        createdAt: minutesAgo(21),
        readBy: ["authority"],
      },
      {
        id: "msg-2",
        conversationId: "conv-1",
        sender: "Rapid Aid Collective",
        senderRole: "ngo",
        text: "Boat-2 rerouted, ETA 14 minutes. Uploading route snapshot.",
        createdAt: minutesAgo(14),
        readBy: ["ngo"],
        pinned: true,
      },
      {
        id: "msg-3",
        conversationId: "conv-1",
        sender: "Field Unit East",
        senderRole: "team",
        text: "Water level rising. Prioritize elder evacuation first.",
        createdAt: minutesAgo(5),
        readBy: ["team"],
      },
    ],
  },
  {
    id: "conv-2",
    title: "District Coordination",
    participants: ["Authority Desk", "Urban Relief Network"],
    participantRoles: ["authority", "ngo"],
    unreadCount: 1,
    updatedAt: minutesAgo(16),
    messages: [
      {
        id: "msg-4",
        conversationId: "conv-2",
        sender: "Urban Relief Network",
        senderRole: "ngo",
        text: "Can we get transport support for overnight shelter relocation?",
        createdAt: minutesAgo(16),
        readBy: ["ngo"],
      },
      {
        id: "msg-5",
        conversationId: "conv-2",
        sender: "Authority Desk",
        senderRole: "authority",
        text: "Approved. Dispatching municipal buses in 20 minutes.",
        createdAt: minutesAgo(11),
        readBy: ["authority"],
      },
    ],
  },
  {
    id: "conv-3",
    title: "NGO Internal - South Cluster",
    participants: ["Rapid Aid Collective", "Urban Relief Network"],
    participantRoles: ["ngo", "ngo"],
    unreadCount: 0,
    updatedAt: minutesAgo(58),
    messages: [
      {
        id: "msg-6",
        conversationId: "conv-3",
        sender: "Urban Relief Network",
        senderRole: "ngo",
        text: "Sharing 120 food packets for Shelter Zone B.",
        createdAt: minutesAgo(58),
        readBy: ["ngo"],
      },
    ],
  },
];

export const broadcastAlerts: BroadcastAlert[] = [
  {
    id: "alert-1",
    title: "Heatwave medical advisory",
    message: "Deploy hydration kiosks and mobile clinics in high-density districts.",
    severity: "medium",
    audience: "all-ngos",
    geoTarget: "Citywide",
    scheduledFor: minutesAgo(120),
    sent: true,
    sentAt: minutesAgo(119),
  },
  {
    id: "alert-2",
    title: "Critical: Building collapse protocol",
    message: "All rescue-capable NGOs to keep one rapid unit on standby for West district.",
    severity: "critical",
    audience: "district-teams",
    geoTarget: "West District",
    scheduledFor: minutesAgo(18),
    sent: true,
    sentAt: minutesAgo(18),
  },
  {
    id: "alert-3",
    title: "Planned river overflow watch",
    message: "Prepare temporary shelter expansion and supply chains for East river wards.",
    severity: "high",
    audience: "selected-ngos",
    geoTarget: "East District",
    scheduledFor: new Date(now + 45 * 60 * 1000).toISOString(),
    sent: false,
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "log-1",
    actor: "Commissioner Anita Rao",
    actorRole: "authority",
    action: "Escalated incident",
    entityType: "incident",
    entityId: "INC-2407",
    createdAt: minutesAgo(9),
    details: "Escalated to regional rescue due to trapped residents and SLA risk.",
    visibleTo: ["authority"],
  },
  {
    id: "log-2",
    actor: "Rapid Aid Collective",
    actorRole: "ngo",
    action: "Posted field update",
    entityType: "message",
    entityId: "conv-1",
    createdAt: minutesAgo(14),
    details: "Boat-2 ETA posted with revised route screenshot.",
    visibleTo: ["authority", "ngo"],
  },
  {
    id: "log-3",
    actor: "System",
    actorRole: "system",
    action: "Broadcast dispatch",
    entityType: "broadcast",
    entityId: "alert-2",
    createdAt: minutesAgo(18),
    details: "Critical protocol sent to district teams.",
    visibleTo: ["authority", "ngo"],
  },
  {
    id: "log-4",
    actor: "Verification Desk",
    actorRole: "team",
    action: "Marked duplicate",
    entityType: "incident",
    entityId: "INC-2411",
    createdAt: minutesAgo(13),
    details: "Possible overlap with INC-2404 pending confirmation.",
    visibleTo: ["authority"],
  },
  {
    id: "log-5",
    actor: "Urban Relief Network",
    actorRole: "ngo",
    action: "Resource reservation",
    entityType: "resource",
    entityId: "res-3",
    createdAt: minutesAgo(23),
    details: "Reserved 110 food packets for shelter transfer mission.",
    visibleTo: ["authority", "ngo"],
  },
];

export const incidentTimeline: ActivityEntry[] = [
  {
    id: "act-1",
    incidentId: "INC-2401",
    actor: "Call Center",
    actorRole: "team",
    content: "Incident received and geo-located automatically.",
    createdAt: minutesAgo(40),
  },
  {
    id: "act-2",
    incidentId: "INC-2401",
    actor: "Rahul Verma",
    actorRole: "authority",
    content: "Verification team dispatched with trauma unit.",
    createdAt: minutesAgo(35),
  },
  {
    id: "act-3",
    incidentId: "INC-2401",
    actor: "Rapid Aid Collective",
    actorRole: "ngo",
    content: "Ambulance support acknowledged. ETA 10 minutes.",
    createdAt: minutesAgo(29),
    mentions: ["@authority"],
  },
  {
    id: "act-4",
    incidentId: "INC-2401",
    actor: "Rahul Verma",
    actorRole: "authority",
    content: "Pinned note: maintain alternate lane clearance for evac route.",
    createdAt: minutesAgo(24),
    pinned: true,
  },
  {
    id: "act-5",
    incidentId: "INC-2401",
    actor: "Field Unit Central",
    actorRole: "team",
    content: "Two victims stabilized. Transfer underway.",
    createdAt: minutesAgo(15),
  },
  {
    id: "act-6",
    incidentId: "INC-2402",
    actor: "Meera Pillai",
    actorRole: "authority",
    content: "Evacuation perimeter established. Need two additional tankers.",
    createdAt: minutesAgo(60),
  },
  {
    id: "act-7",
    incidentId: "INC-2404",
    actor: "Rapid Aid Collective",
    actorRole: "ngo",
    content: "Boat-2 dispatched with medical volunteers.",
    createdAt: minutesAgo(14),
    edited: true,
  },
  {
    id: "act-8",
    incidentId: "INC-2407",
    actor: "Escalation Desk",
    actorRole: "authority",
    content: "Regional heavy-lift team requested. Awaiting acknowledgment.",
    createdAt: minutesAgo(8),
    mentions: ["@ngo", "@team"],
  },
];

export const supportRequests: SupportRequest[] = [
  {
    id: "sup-1",
    incidentId: "INC-2406",
    requestedByNgoId: "ngo-02",
    type: "food",
    status: "acknowledged",
    createdAt: minutesAgo(31),
    note: "Need 250 extra packets before 20:00 shelter distribution.",
  },
  {
    id: "sup-2",
    incidentId: "INC-2407",
    requestedByNgoId: "ngo-04",
    type: "ambulance",
    status: "approved",
    createdAt: minutesAgo(18),
    note: "Require two high-capacity ambulances for collapse site.",
  },
  {
    id: "sup-3",
    incidentId: "INC-2405",
    requestedByNgoId: "ngo-03",
    type: "transport",
    status: "dispatched",
    createdAt: minutesAgo(44),
    note: "Safe transport needed for survivor relocation.",
  },
];

export const assignmentCards: AssignmentCard[] = [
  {
    id: "as-1",
    incidentId: "INC-2403",
    title: "Missing child support alert",
    priority: "high",
    location: "North Bus Depot",
    assignedTo: "Unassigned",
    etaMinutes: 20,
    updatesCount: 3,
    column: "unassigned",
  },
  {
    id: "as-2",
    incidentId: "INC-2405",
    title: "Women safety distress",
    priority: "high",
    location: "Grand Rail Stop",
    assignedTo: "Women Safe Response",
    etaMinutes: 11,
    updatesCount: 10,
    column: "assigned",
  },
  {
    id: "as-3",
    incidentId: "INC-2404",
    title: "Flooded lane rescue",
    priority: "high",
    location: "Riverbank Lane",
    assignedTo: "Rapid Aid Collective",
    etaMinutes: 14,
    updatesCount: 9,
    column: "acknowledged",
  },
  {
    id: "as-4",
    incidentId: "INC-2402",
    title: "Settlement fire response",
    priority: "critical",
    location: "Ward 7",
    assignedTo: "Civic Rescue Trust",
    etaMinutes: 6,
    updatesCount: 18,
    column: "in-progress",
  },
  {
    id: "as-5",
    incidentId: "INC-2406",
    title: "Community kitchen shortage",
    priority: "medium",
    location: "Shelter Zone B",
    assignedTo: "Urban Relief Network",
    etaMinutes: 30,
    updatesCount: 2,
    column: "waiting-resource",
  },
  {
    id: "as-6",
    incidentId: "INC-2408",
    title: "Shelter overcrowding",
    priority: "medium",
    location: "Community Grounds",
    assignedTo: "Urban Relief Network",
    etaMinutes: 0,
    updatesCount: 6,
    column: "resolved",
  },
  {
    id: "as-7",
    incidentId: "INC-2410",
    title: "Evacuation support",
    priority: "low",
    location: "Maple Apartments",
    assignedTo: "Rapid Aid Collective",
    etaMinutes: 0,
    updatesCount: 16,
    column: "closed",
  },
];

export const roleQuickActions: Record<Role, string[]> = {
  authority: [
    "Create Emergency Broadcast",
    "Create Incident Manually",
    "Assign Request",
    "Post Advisory Update",
    "Request NGO Support",
  ],
  ngo: [
    "Team Dispatch Update",
    "Resource Availability Update",
    "Need Support Request",
    "Volunteer Call",
    "Situation Update for Authority",
  ],
};
