import { SosMockContracts } from "@/web/types";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60 * 1000).toISOString();

export const initialMockContracts: SosMockContracts = {
  contacts: [
    {
      id: "ct-01",
      name: "Arun Mehta",
      phone: "+91-9810012345",
      altPhone: "+91-9910012345",
      relation: "Family",
      priority: 1,
      activeForSos: true,
      notes: "Lives 10 minutes away.",
    },
    {
      id: "ct-02",
      name: "Nisha Kapoor",
      phone: "+91-9820013322",
      relation: "Friend",
      priority: 2,
      activeForSos: true,
      notes: "Works near the metro station.",
    },
    {
      id: "ct-03",
      name: "Inspector Priya Rao",
      phone: "+91-9837712345",
      relation: "Police",
      priority: 3,
      activeForSos: false,
      notes: "Use for police escalation only.",
    },
  ],
  incidents: [
    {
      id: "SOS-2026-1142",
      type: "sos",
      sourceType: "self",
      title: "Late night commute distress",
      description: "User triggered SOS from a transit stop and requested live tracking.",
      severity: "high",
      status: "waiting-response",
      urgencyFlag: true,
      location: {
        lat: 28.6139,
        lng: 77.209,
        address: "Gate 2, Rajiv Chowk Metro",
        area: "Connaught Place",
        district: "New Delhi",
        state: "Delhi",
      },
      notifiedContacts: [
        {
          id: "ns-01",
          incidentId: "SOS-2026-1142",
          contactId: "ct-01",
          contactName: "Arun Mehta",
          channel: "sms",
          status: "success",
          sentAt: minutesAgo(6),
          updatedAt: minutesAgo(6),
        },
        {
          id: "ns-02",
          incidentId: "SOS-2026-1142",
          contactId: "ct-02",
          contactName: "Nisha Kapoor",
          channel: "push",
          status: "pending",
          sentAt: minutesAgo(6),
          updatedAt: minutesAgo(6),
        },
        {
          id: "ns-03",
          incidentId: "SOS-2026-1142",
          contactId: "ct-03",
          contactName: "Inspector Priya Rao",
          channel: "voice",
          status: "failed",
          sentAt: minutesAgo(5),
          updatedAt: minutesAgo(5),
          retryCount: 1,
        },
      ],
      attachments: [{ id: "at-01", type: "voice", label: "voice-note-1", createdAt: minutesAgo(5) }],
      authorityAssignee: {
        name: "Inspector Vivek Sharma",
        station: "Connaught Place PS",
        contact: "+91-1121002200",
      },
      verificationFlags: {
        authorityVerified: true,
        ngoLinked: false,
        evidenceReviewed: false,
      },
      categoryTags: ["women-safety", "night-travel"],
      countdownSeconds: 5,
      silentMode: false,
      fakeCallEnabled: true,
      createdAt: minutesAgo(7),
      updatedAt: minutesAgo(2),
    },
    {
      id: "SPE-2026-9981",
      type: "spectator-alert",
      sourceType: "spectator",
      title: "Roadside assault spotted",
      description: "A bystander submitted an immediate spectator alert and a location marker.",
      severity: "critical",
      status: "on-scene",
      urgencyFlag: true,
      location: {
        lat: 28.5211,
        lng: 77.184,
        address: "Ring Road signal, Lajpat Nagar",
        area: "Lajpat Nagar",
        district: "South Delhi",
        state: "Delhi",
      },
      notifiedContacts: [],
      attachments: [
        { id: "at-02", type: "photo", label: "scene-photo-a", createdAt: minutesAgo(41) },
        { id: "at-03", type: "video", label: "scene-video-a", createdAt: minutesAgo(39) },
      ],
      authorityAssignee: {
        name: "SI Rohit Gulati",
        station: "Lajpat Nagar PS",
        contact: "+91-1122401100",
      },
      verificationFlags: {
        authorityVerified: true,
        ngoLinked: true,
        evidenceReviewed: true,
      },
      categoryTags: ["violence", "public-space"],
      createdAt: minutesAgo(44),
      updatedAt: minutesAgo(4),
    },
    {
      id: "REP-2026-6650",
      type: "report",
      sourceType: "report",
      title: "Shelter abuse complaint",
      description: "Reporter shared possible abuse in a relief shelter with a witness statement.",
      severity: "high",
      status: "accepted",
      urgencyFlag: true,
      location: {
        address: "Temporary shelter block C",
        area: "Yamuna Pushta",
        district: "East Delhi",
        state: "Delhi",
      },
      notifiedContacts: [],
      attachments: [{ id: "at-04", type: "document", label: "witness-statement", createdAt: minutesAgo(170) }],
      verificationFlags: {
        authorityVerified: false,
        ngoLinked: true,
        evidenceReviewed: false,
      },
      categoryTags: ["shelter", "protection"],
      createdAt: minutesAgo(180),
      updatedAt: minutesAgo(22),
    },
    {
      id: "SOS-2026-0103",
      type: "sos",
      sourceType: "self",
      title: "Resolved home intrusion scare",
      description: "Emergency alert sent and later closed as safe after a police check.",
      severity: "medium",
      status: "resolved",
      urgencyFlag: false,
      location: {
        address: "Sector 62, Noida",
        area: "Sector 62",
        district: "Gautam Buddha Nagar",
        state: "Uttar Pradesh",
      },
      notifiedContacts: [
        {
          id: "ns-04",
          incidentId: "SOS-2026-0103",
          contactId: "ct-02",
          contactName: "Nisha Kapoor",
          channel: "sms",
          status: "success",
          sentAt: minutesAgo(510),
          updatedAt: minutesAgo(510),
        },
      ],
      attachments: [],
      verificationFlags: {
        authorityVerified: true,
        ngoLinked: false,
        evidenceReviewed: true,
      },
      categoryTags: ["home-safety"],
      countdownSeconds: 3,
      silentMode: true,
      fakeCallEnabled: false,
      createdAt: minutesAgo(520),
      updatedAt: minutesAgo(490),
      resolvedAt: minutesAgo(490),
    },
  ],
  incidentTimeline: [
    {
      id: "tl-01",
      incidentId: "SOS-2026-1142",
      actor: "Citizen App",
      actorRole: "system",
      eventType: "status",
      message: "SOS request created and encrypted payload sent.",
      createdAt: minutesAgo(7),
      verificationFlag: true,
    },
    {
      id: "tl-02",
      incidentId: "SOS-2026-1142",
      actor: "Contact Notifier",
      actorRole: "system",
      eventType: "status",
      message: "Trusted contacts notified across SMS, push, and voice channels.",
      createdAt: minutesAgo(6),
    },
    {
      id: "tl-03",
      incidentId: "SOS-2026-1142",
      actor: "Tracking Service",
      actorRole: "system",
      eventType: "location",
      message: "Tracking active with live location pings every 5 seconds.",
      createdAt: minutesAgo(5),
    },
    {
      id: "tl-04",
      incidentId: "SOS-2026-1142",
      actor: "Authority Desk",
      actorRole: "authority",
      eventType: "verification",
      message: "Incident accepted by the command desk; responder dispatched.",
      createdAt: minutesAgo(3),
      verificationFlag: true,
    },
    {
      id: "tl-05",
      incidentId: "SPE-2026-9981",
      actor: "PCR Van 12",
      actorRole: "authority",
      eventType: "status",
      message: "On scene. Safety perimeter established.",
      createdAt: minutesAgo(4),
      verificationFlag: true,
    },
    {
      id: "tl-06",
      incidentId: "REP-2026-6650",
      actor: "Protection NGO Desk",
      actorRole: "ngo",
      eventType: "note",
      message: "Victim support counselor allocated.",
      createdAt: minutesAgo(18),
    },
    {
      id: "tl-07",
      incidentId: "SOS-2026-0103",
      actor: "Citizen",
      actorRole: "citizen",
      eventType: "status",
      message: "User confirmed safety and closed the incident.",
      createdAt: minutesAgo(490),
    },
  ],
  notificationStatuses: [
    {
      id: "ns-01",
      incidentId: "SOS-2026-1142",
      contactId: "ct-01",
      contactName: "Arun Mehta",
      channel: "sms",
      status: "success",
      sentAt: minutesAgo(6),
      updatedAt: minutesAgo(6),
    },
    {
      id: "ns-02",
      incidentId: "SOS-2026-1142",
      contactId: "ct-02",
      contactName: "Nisha Kapoor",
      channel: "push",
      status: "pending",
      sentAt: minutesAgo(6),
      updatedAt: minutesAgo(6),
    },
    {
      id: "ns-03",
      incidentId: "SOS-2026-1142",
      contactId: "ct-03",
      contactName: "Inspector Priya Rao",
      channel: "voice",
      status: "failed",
      sentAt: minutesAgo(5),
      updatedAt: minutesAgo(5),
      retryCount: 1,
    },
    {
      id: "ns-04",
      incidentId: "SOS-2026-0103",
      contactId: "ct-02",
      contactName: "Nisha Kapoor",
      channel: "sms",
      status: "success",
      sentAt: minutesAgo(510),
      updatedAt: minutesAgo(510),
    },
  ],
  socialPosts: [
    {
      id: "post-001",
      author: { name: "SafeStreets Delhi", role: "ngo", verified: true },
      title: "Night escort volunteers active",
      content:
        "Volunteer escort corridors are active between 9 PM and 1 AM from Rajiv Chowk to Patel Chowk. Request support if you are stranded.",
      locationText: "Central Delhi",
      createdAt: minutesAgo(35),
      category: "relief",
      postType: "relief",
      tags: ["#nightsafety", "#escorthelp"],
      campaign: {
        goalAmount: 250000,
        raisedAmount: 138000,
        contributors: 412,
      },
      engagement: {
        likes: 812,
        comments: 142,
        shares: 76,
        supports: 201,
      },
      commentsPreview: [
        { id: "c1", author: "Ritika", text: "Thank you for sharing this route map." },
        { id: "c2", author: "Ajay", text: "Can volunteers assist near Gate 4 also?" },
      ],
      supporters: [
        { id: "sup-1", name: "Metro Civic Trust", type: "donor" },
        { id: "sup-2", name: "North Campus Volunteers", type: "supporter" },
      ],
      isSaved: true,
      isSupported: false,
      isUrgent: true,
      isNearby: true,
      isVerified: true,
    },
    {
      id: "post-002",
      author: { name: "Delhi Command Updates", role: "authority", verified: true },
      content:
        "Flood advisory: avoid underpass lanes in East district for the next 4 hours. Response teams and shelters are active.",
      locationText: "East Delhi",
      createdAt: minutesAgo(55),
      category: "verified",
      postType: "community-alert",
      tags: ["#advisory", "#flood"],
      media: [{ id: "pm-01", type: "photo", label: "flood-advisory-map", createdAt: minutesAgo(54) }],
      engagement: {
        likes: 640,
        comments: 84,
        shares: 190,
        supports: 110,
      },
      commentsPreview: [{ id: "c3", author: "Public Desk", text: "Shelter addresses posted in comments." }],
      supporters: [{ id: "sup-3", name: "District Relief Desk", type: "supporter" }],
      isSaved: false,
      isSupported: true,
      isUrgent: true,
      isNearby: false,
      isVerified: true,
    },
    {
      id: "post-003",
      author: { name: "Northeast Medics", role: "ngo", verified: true },
      content:
        "Mobile trauma unit is now at the Trilokpuri shelter cluster. Priority for children and elderly with chronic conditions.",
      locationText: "Trilokpuri",
      createdAt: minutesAgo(90),
      category: "medical",
      postType: "medical",
      tags: ["#medical", "#sheltercare"],
      media: [{ id: "pm-02", type: "video", label: "mobile-clinic-update", createdAt: minutesAgo(88) }],
      engagement: {
        likes: 420,
        comments: 62,
        shares: 33,
        supports: 95,
      },
      commentsPreview: [{ id: "c4", author: "Seema", text: "Unit available till what time?" }],
      supporters: [{ id: "sup-4", name: "Health Donor Pool", type: "donor" }],
      isSaved: false,
      isSupported: false,
      isUrgent: false,
      isNearby: true,
      isVerified: true,
    },
    {
      id: "post-004",
      author: { name: "Community Safety Circle", role: "citizen", verified: false },
      content: "Sharing emergency legal helplines and survivor counseling references for late-night travelers.",
      createdAt: minutesAgo(120),
      category: "awareness",
      postType: "awareness",
      tags: ["#legalaid", "#awareness"],
      engagement: {
        likes: 190,
        comments: 36,
        shares: 28,
        supports: 44,
      },
      commentsPreview: [{ id: "c5", author: "Mona", text: "Please post the Hindi list too." }],
      supporters: [],
      isSaved: true,
      isSupported: false,
      isUrgent: false,
      isNearby: false,
      isVerified: false,
    },
    {
      id: "post-005",
      author: { name: "Feeding Hands India", role: "ngo", verified: true },
      title: "Meal support open near shelter cluster",
      content: "Fresh food packets are available for 300 families near the camp gate till 11 PM.",
      locationText: "Mayur Vihar",
      createdAt: minutesAgo(22),
      category: "food-support",
      postType: "food-support",
      tags: ["#foodsupport", "#relief"],
      media: [{ id: "pm-03", type: "photo", label: "meal-kits", createdAt: minutesAgo(21) }],
      engagement: {
        likes: 258,
        comments: 31,
        shares: 18,
        supports: 73,
      },
      commentsPreview: [{ id: "c6", author: "Shiv", text: "Can senior citizens get home delivery?" }],
      supporters: [
        { id: "sup-5", name: "Annapurna Trust", type: "donor" },
        { id: "sup-6", name: "Ward Volunteers", type: "supporter" },
      ],
      isSaved: false,
      isSupported: true,
      isUrgent: false,
      isNearby: true,
      isVerified: true,
    },
  ],
  resources: [
    {
      id: "res-00",
      name: "National Emergency Response 112",
      category: "helpline",
      district: "National",
      state: "India",
      phone: "112",
      address: "Integrated emergency response number",
      availability: "24x7",
      verified: true,
      lastUpdated: minutesAgo(8),
      notes: "Police, fire, and medical escalation.",
    },
    {
      id: "res-01",
      name: "Women Helpline 181",
      category: "helpline",
      district: "New Delhi",
      state: "Delhi",
      phone: "181",
      address: "State women support control room",
      availability: "24x7",
      verified: true,
      lastUpdated: minutesAgo(20),
      notes: "Fast escalation for immediate danger.",
    },
    {
      id: "res-02",
      name: "District Shelter Hub",
      category: "shelter",
      district: "East Delhi",
      state: "Delhi",
      address: "Mayur Vihar Phase 1 Community Hall",
      availability: "24x7",
      verified: true,
      lastUpdated: minutesAgo(90),
      notes: "Capacity updates every 2 hours.",
    },
    {
      id: "res-03",
      name: "Legal Aid Desk",
      category: "legal",
      district: "Noida",
      state: "Uttar Pradesh",
      phone: "+91-1204509988",
      address: "Sector 18 Civil Court Annex",
      availability: "limited",
      verified: true,
      lastUpdated: minutesAgo(210),
      notes: "Fast-track FIR and legal consults.",
    },
    {
      id: "res-04",
      name: "Psychological First Aid Center",
      category: "psychosocial",
      district: "Ghaziabad",
      state: "Uttar Pradesh",
      phone: "+91-1207788991",
      address: "Kaushambi Wellness Block",
      availability: "day",
      verified: true,
      lastUpdated: minutesAgo(140),
      notes: "Trauma-informed counseling support.",
    },
    {
      id: "res-05",
      name: "Women and Child Support Center",
      category: "women-child",
      district: "South Delhi",
      state: "Delhi",
      phone: "+91-1140055501",
      address: "AIIMS Extension Road",
      availability: "day",
      verified: true,
      lastUpdated: minutesAgo(50),
      notes: "Medical, legal, and psychosocial support.",
    },
  ],
  revelationReports: [
    {
      id: "REV-2026-0021",
      category: "corruption",
      severity: "high",
      anonymous: true,
      includeLocation: true,
      title: "Diversion of relief ration",
      description: "Relief stock was marked as distributed but never reached listed families in ward records.",
      location: {
        address: "Ward 11 ration depot",
        area: "Seelampur",
        district: "East Delhi",
        state: "Delhi",
      },
      attachments: [{ id: "ra-1", name: "stock-register-photo.jpg", type: "image/jpeg", mediaType: "photo" }],
      status: "under-review",
      createdAt: minutesAgo(610),
    },
    {
      id: "REV-2026-0043",
      category: "harassment",
      severity: "high",
      anonymous: false,
      includeLocation: true,
      title: "Shelter harassment complaint",
      description: "Repeated abuse by a supervisor against women beneficiaries at a temporary shelter.",
      location: {
        address: "Zone B Shelter",
        area: "Yamuna Pushta",
        district: "East Delhi",
        state: "Delhi",
      },
      attachments: [],
      status: "submitted",
      createdAt: minutesAgo(140),
    },
  ],
  draftReports: [
    {
      id: "draft-9001",
      category: "abuse",
      severity: "medium",
      anonymous: true,
      includeLocation: false,
      title: "Pending witness statement",
      description: "Draft note on repeated verbal abuse inside the transit waiting area.",
      attachments: [{ id: "dr-a1", name: "voice-note.mp3", type: "audio/mpeg", mediaType: "voice" }],
      locationText: "",
      updatedAt: minutesAgo(35),
    },
  ],
  authorityQueue: [
    {
      incidentId: "SOS-2026-1142",
      assignedTo: "Inspector Vivek Sharma",
      district: "New Delhi",
      severity: "high",
      status: "waiting-response",
      type: "sos",
      verified: true,
      receivedAt: minutesAgo(7),
    },
    {
      incidentId: "SPE-2026-9981",
      assignedTo: "SI Rohit Gulati",
      district: "South Delhi",
      severity: "critical",
      status: "on-scene",
      type: "spectator-alert",
      verified: true,
      receivedAt: minutesAgo(44),
    },
    {
      incidentId: "REP-2026-6650",
      district: "East Delhi",
      severity: "high",
      status: "accepted",
      type: "report",
      verified: false,
      receivedAt: minutesAgo(180),
    },
  ],
  ngoCampaigns: [
    {
      id: "camp-11",
      title: "Safe Night Transit Volunteers",
      region: "Central + South Delhi",
      category: "rehabilitation",
      active: true,
      targetAmount: 500000,
      raisedAmount: 318000,
      volunteersActive: 82,
      requestsOpen: 19,
    },
    {
      id: "camp-12",
      title: "Flood Relief Medical Support",
      region: "East Delhi",
      category: "medical",
      active: true,
      targetAmount: 850000,
      raisedAmount: 420000,
      volunteersActive: 61,
      requestsOpen: 27,
    },
    {
      id: "camp-13",
      title: "Shelter Nutrition Drive",
      region: "Noida + Ghaziabad",
      category: "food",
      active: false,
      targetAmount: 300000,
      raisedAmount: 300000,
      volunteersActive: 0,
      requestsOpen: 0,
    },
  ],
  ngoDirectory: [
    {
      id: "ngo-01",
      name: "SafeStreets Delhi",
      category: "Women Safety",
      location: "New Delhi, Delhi",
      scope: "district",
      description: "Runs safe commute escorts, community response groups, and night transit assistance.",
      contactPhone: "+91-1140100101",
      contactEmail: "support@safestreets.org",
      fundraising: {
        raised: 318000,
        goal: 500000,
      },
      campaigns: ["camp-11"],
      services: ["Escort support", "Volunteer dispatch", "Crisis guidance"],
    },
    {
      id: "ngo-02",
      name: "Northeast Medics",
      category: "Medical Relief",
      location: "East Delhi, Delhi",
      scope: "state",
      description: "Deploys mobile trauma units, field medics, and emergency support teams.",
      contactPhone: "+91-1140100202",
      contactEmail: "ops@northeastmedics.org",
      fundraising: {
        raised: 420000,
        goal: 850000,
      },
      campaigns: ["camp-12"],
      services: ["Mobile clinic", "Emergency kits", "Triage support"],
    },
    {
      id: "ngo-03",
      name: "Feeding Hands India",
      category: "Food Support",
      location: "Multiple States, India",
      scope: "national",
      description: "Coordinates food packet distribution for high-risk and displaced families.",
      contactPhone: "+91-1140100303",
      contactEmail: "hello@feedinghands.in",
      fundraising: {
        raised: 790000,
        goal: 1200000,
      },
      campaigns: [],
      services: ["Meal distribution", "Dry ration kits", "Field kitchens"],
    },
    {
      id: "ngo-04",
      name: "Global Relief Link",
      category: "Disaster Response",
      location: "Asia Pacific Operations",
      scope: "global",
      description: "Supports cross-border response partnerships and emergency donor logistics.",
      contactPhone: "+91-1140100404",
      contactEmail: "aid@globalrelieflink.org",
      fundraising: {
        raised: 2100000,
        goal: 3000000,
      },
      campaigns: [],
      services: ["International aid", "Rapid funding", "Partner coordination"],
    },
  ],
  userCampaigns: [
    {
      id: "uc-101",
      title: "Safe Route Mapping for Students",
      summary: "Community volunteers collect and verify safer late-evening commute paths.",
      category: "awareness",
      targetAmount: 180000,
      raisedAmount: 62000,
      visibility: "public",
      status: "active",
      createdAt: minutesAgo(980),
    },
    {
      id: "uc-102",
      title: "Neighborhood Emergency Kits",
      summary: "Resident-led emergency kit distribution for high-risk blocks.",
      category: "relief",
      targetAmount: 240000,
      raisedAmount: 240000,
      visibility: "trusted",
      status: "closed",
      createdAt: minutesAgo(2500),
    },
  ],
  contributions: [
    {
      id: "con-01",
      title: "Safe Night Transit donor contribution",
      amount: 1200,
      category: "donation",
      status: "active",
      createdAt: minutesAgo(320),
    },
    {
      id: "con-02",
      title: "Volunteer shift - shelter support",
      amount: 0,
      category: "volunteer",
      status: "fulfilled",
      createdAt: minutesAgo(1560),
    },
    {
      id: "con-03",
      title: "Neighborhood Emergency Kits support",
      amount: 850,
      category: "campaign",
      status: "closed",
      createdAt: minutesAgo(2800),
    },
  ],
  transparencyEntries: [
    {
      id: "tr-100",
      district: "New Delhi",
      state: "Delhi",
      category: "contribution",
      title: "Women safety donor pool",
      amount: 240000,
      verificationBadge: "verified",
      proofCount: 18,
      updatedAt: minutesAgo(30),
    },
    {
      id: "tr-101",
      district: "East Delhi",
      state: "Delhi",
      category: "allocation",
      title: "Medical kits allocated to flood units",
      quantity: "640 kits",
      verificationBadge: "verified",
      proofCount: 9,
      updatedAt: minutesAgo(70),
    },
    {
      id: "tr-102",
      district: "South Delhi",
      state: "Delhi",
      category: "distribution",
      title: "Night escort meal support",
      quantity: "1,250 meal packs",
      verificationBadge: "pending",
      proofCount: 4,
      updatedAt: minutesAgo(135),
    },
    {
      id: "tr-103",
      district: "Noida",
      state: "Uttar Pradesh",
      category: "audit",
      title: "Quarterly NGO ledger review",
      amount: 0,
      verificationBadge: "flagged",
      proofCount: 2,
      updatedAt: minutesAgo(490),
    },
  ],
  profile: {
    name: "Ananya Sharma",
    email: "ananya@sos.app",
    phone: "+91-9876543210",
    address: "Sector 62, Noida, Uttar Pradesh",
  },
  userSettings: {
    countdownSeconds: 5,
    silentMode: false,
    autoRecord: true,
    continuousLocationShare: true,
    vibration: true,
    fakeCallShortcut: true,
    distressLanguage: "en",
    language: "en",
  },
  permissionsStatus: {
    location: "granted",
    notifications: "granted",
    microphone: "prompt",
    camera: "granted",
  },
  dashboardWidgets: {
    urgentAlerts: [
      { id: "ua-1", title: "High-risk commute alert in CP corridor", severity: "critical" },
      { id: "ua-2", title: "Shelter abuse investigation in progress", severity: "high" },
      { id: "ua-3", title: "East district flood lane closure", severity: "medium" },
    ],
    nearbyResources: [
      { id: "nr-1", label: "Women Helpline Node", distanceKm: 1.2 },
      { id: "nr-2", label: "Transit Police Booth", distanceKm: 0.8 },
      { id: "nr-3", label: "Emergency Legal Desk", distanceKm: 3.6 },
    ],
    trendingTags: ["#nightsafety", "#floodresponse", "#verifiedupdate", "#legalaid"],
    topContributors: [
      { id: "tc-1", name: "Metro Civic Trust", amount: 150000 },
      { id: "tc-2", name: "Rao Family Fund", amount: 92000 },
      { id: "tc-3", name: "North Medics Collective", amount: 64000 },
    ],
    safetyTips: [
      "Share your route before late travel.",
      "Keep emergency contacts prioritized.",
      "Use silent mode only when direct risk is high.",
    ],
    activeCampaigns: [
      { id: "ac-1", title: "Safe Night Transit", progress: 64 },
      { id: "ac-2", title: "Flood Relief Medical", progress: 49 },
      { id: "ac-3", title: "Shelter Counseling", progress: 71 },
    ],
  },
  authSession: {
    isAuthenticated: false,
    mobile: "",
    otpVerified: false,
    currentRole: "citizen",
  },
};
